### ISSUE TITLE
README issue

### ISSUE THREAD

**Issue by gonzaloserrano** [shen2/FluentCQL#2]
Hi,

In the `INSERT COMMAND` section the operation is a select, not an insert. Also there is a missing `(`. Could you provide an insert example?

Then `ActiveObject-like Usage` should be `ActiveRecord-like usage` http://en.wikipedia.org/wiki/Active_record_pattern

Thanks

**Comment by gonzaloserrano** [comment]
Thanks for the quick response. Could you provide an `INSERT` example also? Not really sure how it would work.

edit: also you forgot to add the missing `(` as i reported before.

**Comment by shen2** [comment]
This revision may be helpful.
https://github.com/shen2/FluentCQL/commit/5a5590a5027318e128e548425c9a81a6c2793379

**Comment by gonzaloserrano** [comment]
Much better, thanks :)
