### ISSUE TITLE
Invalid: Expected 4 or 0 byte int (8)

### ISSUE THREAD

**Issue by muradkarakas** [shen2/FluentCQL#4]
Hi All

class Test extends \FluentCQL\Table{

```
protected static $_name = 'test';

protected static $_primary = array('test');

protected static $_columns = array(
        'test' => Cassandra\Type\Base::VARCHAR,
        'user_id' => Cassandra\Type\Base::BIGINT,
        'test_status' => Cassandra\Type\Base::INT,
        'default_test' => Cassandra\Type\Base::INT,
        'created' => Cassandra\Type\Base::INT,
        'changed' => Cassandra\Type\Base::INT,
);
```

when I try to insert a row into the table above with the code below, I am getting the error message "Invalid: Expected 4 or 0 byte int (8)"

$response = Test ::insertRow( [
                'test' => 'test data',
                'user_id' => 1,
                'test_status' => 1, 
                'default_test' => 1,
                'created' => 1,
                'changed' => 1,
              ] );

I can insert columns with "int" type, but I couldn't insert "Bigint". 
I try to cast to "new Cassandra\Type\Bigint(1)" but failed with 
      "Notice: Object of class Cassandra\Type\Bigint could not be converted to int in C:\wamp\www\cassandra\cassandra_php_driver\Type\Bigint.php on line 10" 
error message.

What is my mistake ? 
Thank you

**Comment by shen2** [comment]
what's your table schema?  Your input should strictly obey the schema.

**Comment by muradkarakas** [comment]
Thank you for reply shen2. Here is the table creation script

CREATE TABLE test (
    test text,
    changed int,
    test_status int,
    created int,
    default_test int,
    user_id bigint,
    PRIMARY KEY (test)
) WITH bloom_filter_fp_chance = 0.01
AND comment = ''
AND dclocal_read_repair_chance = 0.1
AND read_repair_chance = 0.0
AND caching = {
    'keys' : 'ALL',
    'rows_per_partition' : 'NONE'
}
AND compression = {
    'sstable_compression' : 'LZ4Compressor'
}
AND compaction = {
    'class' : 'SizeTieredCompactionStrategy'
};

I have generated it form datastax devcenter.

**Comment by shen2** [comment]
Is your system 32-bit or 64-bit?

**Comment by muradkarakas** [comment]
Hi shen

it is 32bit.

Wamp Version
   2.5
Apache Version :
    2.4.9   - Documentation
PHP Version :
    5.5.12   - Documentation
Server Software:
    Apache/2.4.9 (Win32) PHP/5.5.12

**Comment by shen2** [comment]
php-cassandra cannot support bigint when system is 32-bit

**Comment by muradkarakas** [comment]
Thank you for support shen2. Your support is so important for php developers. I'll try with 64bit installation again.
